import { renderPostgreSql } from '../generation/renderPostgreSql.js';

const DEMO_PLAN = Object.freeze({
  schemaName: 'demo_data',
  tableName: 'sample_records',
  columns: [
    { name: 'id', type: 'integer', nullable: false },
    { name: 'name', type: 'text', nullable: false },
    { name: 'category', type: 'text', nullable: false },
  ],
  rows: [
    [1, 'Ada Lovelace', 'engineering'],
    [2, 'Grace Hopper', 'engineering'],
    [3, 'Katherine Johnson', 'science'],
  ],
  assumptions: [
    'This preview was generated by the deterministic local demo provider.',
    'Demo mode never calls OpenAI or writes to a database.',
  ],
  warnings: ['Demo mode is active; execution is disabled.'],
  model: 'demo-provider',
  promptVersion: 'demo-v1',
});

export const createDemoDatasetPlanner = () => ({
  generate: async () => ({
    ...DEMO_PLAN,
    columns: DEMO_PLAN.columns.map((column) => ({ ...column })),
    rows: DEMO_PLAN.rows.map((row) => [...row]),
    assumptions: [...DEMO_PLAN.assumptions],
    warnings: [...DEMO_PLAN.warnings],
    sql: renderPostgreSql(DEMO_PLAN),
  }),
});
